FROM postgres:13.12

# Set environment variables for PostgreSQL
# ENV POSTGRES_USER=postgres
# ENV POSTGRES_PASSWORD=keko
# ENV POSTGRES_DB=postgres
# ENV POSTGRES_PORT=5433

# ENV  host="localhost"
# ENV  port=5433
# ENV  user="postgres"
# ENV password="keko"
# ENV database="postgres"

# ENV host=bszzomxzh3twyfkna8up-postgresql.services.clever-cloud.com
# ENV port=50013
# ENV user=uttjzcezvawy94ywguq1
# ENV password=FGhKfHaLdjTor1tmuFxe6ewO9rQjsC
# ENV database=bszzomxzh3twyfkna8up

ENV host=blfwgps8wn77kdxbeuck-postgresql.services.clever-cloud.com
ENV port=50013
ENV user=uikzyx7pmcmuaukzmjlp
ENV password=k1hHldg0jYGsWlbfb8XZLcZ2L9nWPJ
ENV database=blfwgps8wn77kdxbeuck



# Expose PostgreSQL default port
EXPOSE 5433

# Start PostgreSQL on container startup
CMD ["postgres"]